[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"


[colors]
[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.normal]
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#928374"      # :: Gray instead of dark gray
red = "#f2594b"        # :: Brighter, more vibrant red
green = "#b8bb26"      # :: Brighter green
yellow = "#fabd2f"     # :: Brighter yellow
blue = "#83a598"       # :: Brighter blue
magenta = "#d3869b"    # :: Slightly brighter magenta
cyan = "#8ec07c"       # :: Brighter cyan
white = "#ebdbb2"      # :: Much brighter white for highlights

[colors.selection]
text = "CellBackground"
background = "#504945"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font]
# size=11.25 # :: 11.25
# size=8.5 # :: 11.25 for smaller resolution displays
size=9 # :: For bigger resolution displays
# size=17.25 # :: 11.25


[window]
option_as_alt = "Both"
padding.x = 14
padding.y = 14
decorations = "None"

# :: MAC
# [terminal.shell]
# program = "/opt/homebrew/bin/fish"


# :: Linux
[terminal.shell]
program = "/usr/bin/fish"

